// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using W5L2.Data;

#nullable disable

namespace W5L2.Migrations
{
    [DbContext(typeof(W5L2Context))]
    partial class W5L2ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("W5L2.Models.UserA", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Age")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID");

                    b.ToTable("UserA", t =>
                        {
                            t.HasCheckConstraint("CK_UserA_Age", "[Age] >= 0 AND [Age] <= 200");
                        });
                });

            modelBuilder.Entity("W5L2.Models.UserB", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("title")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.ToTable("UserB");
                });

            modelBuilder.Entity("W5L2.Models.UserB", b =>
                {
                    b.HasOne("W5L2.Models.UserA", "UserA")
                        .WithOne("UserB")
                        .HasForeignKey("W5L2.Models.UserB", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserA");
                });

            modelBuilder.Entity("W5L2.Models.UserA", b =>
                {
                    b.Navigation("UserB")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
